ktor:
    application:
        modules:
            - com.example.ktor.ApplicationKt.module
    deployment:

    database:
        driver: "org.mariadb.jdbc.Driver"
        url: "jdbc:mariadb://localhost:3307/ociojaen"
        username: "manu"
        password: "ghe9c5ui39h"